const sections=document.querySelectorAll(".section");document.addEventListener("DOMContentLoaded",()=>{console.log("Script loaded and DOM fully parsed");const navLinks=document.querySelectorAll(".nav-btn");navLinks.forEach(link=>{link.addEventListener("click",e=>{const href=link.getAttribute("href");if(!href.startsWith("#")){return}
e.preventDefault();const targetId=href.substring(1);showSection(targetId);history.pushState(null,"",`#${targetId}`)})});window.addEventListener("popstate",()=>{const hash=window.location.hash.substring(1)||"home";console.log("Back/forward navigation detected:",hash);showSection(hash)});const initialHash=window.location.hash.substring(1);if(initialHash){console.log("Page loaded with hash:",initialHash);showSection(initialHash)}else{console.log("Page loaded without hash; showing home");showSection("home")}});function showSection(sectionId){console.log(`Navigating to section: #${sectionId}`);sections.forEach(section=>section.classList.add("hidden"));const target=document.getElementById(sectionId);if(target){target.classList.remove("hidden");console.log(`Section #${sectionId} shown`)}else{console.warn(`Section #${sectionId} not found`)}
if(sectionId!=="home"){document.getElementById("home").classList.add("hidden")}else{document.getElementById("home").classList.remove("hidden")}}
document.addEventListener('DOMContentLoaded',()=>{const audio=document.getElementById('bg-audio');if(audio&&audio.paused){audio.play().catch(()=>{console.log('Autoplay blocked — user must interact')})}});function closeSection(id){document.getElementById(id).classList.add("hidden");hideForm(id+"-form");showSection("home");history.pushState(null,"","#home")}
document.addEventListener("DOMContentLoaded",()=>{const form=document.querySelector('#contact form');form.addEventListener("submit",function(e){e.preventDefault();const formData=new FormData(form);fetch(form.action,{method:form.method,body:formData,headers:{'Accept':'application/json'}}).then(response=>{if(response.ok){form.reset();closeSection('contact',!1);document.getElementById('thank-you-modal').classList.remove('hidden')}else{alert("Something went wrong. Please try again later.")}})})});function handleSubmit(id){const honeypot=document.getElementById(id+"-honeypot").value;if(honeypot!=="")return!1;const submitBtn=document.getElementById(id+"-btn")
submitBtn.disabled=!0;submitBtn.textContent="SUBMITTING...";return!0}
function handleContactSubmit(){const form=document.getElementById('contact-form');const honeypot=document.getElementById('contact-honeypot').value;if(honeypot!=="")return!1;const submitBtn=document.getElementById('contact-btn');submitBtn.disabled=!0;submitBtn.textContent="SUBMITTING...";const formData=new FormData();formData.append("formType","contact");formData.append("name",form.querySelector("#contact-name").value);formData.append("email",form.querySelector("#contact-email").value);formData.append("message",form.querySelector("#contact-message").value);formData.append("company",honeypot);fetch("https://script.google.com/macros/s/AKfycbxxsAyFrKfDfSxWcTsGsaSO8ozHkZMUVkIsJqmnmqW0XciLhJTXEui6YtuX53MJIWCY/exec",{method:'POST',body:formData}).then(res=>res.json()).then(data=>{if(data.success){form.reset();submitBtn.disabled=!1;submitBtn.textContent="SEND MESSAGE";closeSection('contact',!1);document.getElementById('thank-you-modal').classList.remove('hidden')}else{alert("Submission failed. Please try again or contact us at madapplecircus@gmail.com.");submitBtn.disabled=!1;submitBtn.textContent="SEND MESSAGE"}}).catch(err=>{alert("An error occurred. Please try again or contact us at madapplecircus@gmail.com.");submitBtn.disabled=!1;submitBtn.textContent="SEND MESSAGE";console.error(err)});return!1}
document.getElementById('signup_hidden_iframe').addEventListener('load',function(){const form=document.getElementById('mailing-list-form');const name=form.querySelector("#signup-name").value;const email=form.querySelector("#signup-email").value;if(name!==""&&email!=""){form.reset();const submitBtn=form.querySelector("button[type='submit']");submitBtn.disabled=!1;submitBtn.textContent="SUBSCRIBE";closeSection('signup',!1);document.getElementById('signup-success-modal').classList.remove('hidden')}});const burger=document.getElementById('burger');burger.addEventListener('click',()=>{const sidenav=document.getElementById('sidenav');const logo=document.getElementById('mac-logo');const isOpen=sidenav.classList.toggle('open');burger.classList.toggle('open',isOpen);logo.classList.toggle('nav-open',isOpen);burger.setAttribute('aria-expanded',isOpen)});function hideForm(id){const container=document.getElementById(id);const form=container.querySelector('form');if(form){form.reset();[...form.elements].forEach(el=>el.disabled=!0)}
container.style.display='none'}
function showForm(id){const container=document.getElementById(id);const form=container.querySelector('form');container.style.display='flex';[...form.elements].forEach(el=>el.disabled=!1)}
const banner=document.getElementById('cookie-banner');const footer=document.querySelector('footer');function adjustFooter(){if(!footer)return;const bannerHeight=banner.offsetHeight;footer.style.bottom=(bannerHeight+16)+'px'}
function showBanner(){console.log("Show banner")
banner.style.display='flex';adjustFooter()}
function hideBanner(){console.log("Hide banner")
banner.style.display='none';if(footer)footer.style.bottom='1rem'}
if(!localStorage.getItem('cookiesAccepted')){showBanner()}else{loadGA()}
document.getElementById('cookie-accept').addEventListener('click',function(){localStorage.setItem('cookiesAccepted','true');hideBanner();loadGA()});function loadGA(){const gaScript=document.createElement('script');gaScript.src="https://www.googletagmanager.com/gtag/js?id=G-076LPQ12GX";gaScript.async=!0;document.head.appendChild(gaScript);window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}
gtag('js',new Date());gtag('config','G-076LPQ12GX')}
window.addEventListener('resize',function(){if(banner.style.display==='flex')adjustFooter();})